version: "3"
services:
  developer_junior:
    build: ./docker/ubuntu_workstation
    volumes:
      - source_code_ordinary:/home/code
  developer_senior:
    build: ./docker/ubuntu_workstation
    volumes:
      - source_code_ordinary:/home/code/ordinary
      - source_code_critical:/home/code/critical
  admin:
    build: ./docker/admin
  ceo_workstation:
    build: ./docker/ceo
    volumes:
      - bussiness_client_data:/home/client_data
  portoflio_server:
    build: ./docker/web
    ports:
      - "127.0.0.1:3000:8080"
  postfix_server:
    build: ./docker/server

volumes:
  source_code_critical:
  source_code_ordinary:
  bussiness_client_data: