version: '3'

services:
  developer_junior:
    build: ./docker/junior_workstation
    volumes:
      - source_code_ordinary:/home/junior/code
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    command: tail -F anything
    networks:
      - company_machines
    extra_hosts:
      - "cyberpoligon.local:172.19.1.20"
    ports:
      - "8080:8080"
  developer_senior:
    build: ./docker/senior_workstation
    command: tail -F anything
    volumes:
      - source_code_ordinary:/home/senior/code/ordinary
      - source_code_critical:/home/senior/code/critical
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: always
    ports:
      - "5900:5900"
    networks:
      - company_machines
    extra_hosts:
      - "cyberpoligon.local:172.19.1.20"
  admin:
    build: ./docker/admin
    command: tail -F anything
    restart: always
    networks:
      - company_machines
  ceo_workstation:
    build: ./docker/ceo
    command: tail -F anything
    volumes:
      - bussiness_client_data:/home/ceo/client_data
    restart: always
    networks:
      - company_machines
  portoflio_server:
    command: tail -F anything
    build: ./docker/web
    restart: always
    ports:
      - "3000:8080"
  mailserver2:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: cyberpoligon.local
    env_file: mailserver.env
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    ports:
      - "25:25" # SMTP  
      - "143:143" # IMAP4 
      - "465:465" # ESMTP 
      - "587:587" # ESMTP 
      - "993:993" # IMAP4
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      company_machines:
        ipv4_address: 172.19.1.20

networks:
  company_machines:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.1.0/24

volumes:
  source_code_critical:
  source_code_ordinary:
  bussiness_client_data: